define([], function () {
	return {
		PropertyPaneDescription: "Set your configuration below to embed Qlik into SharePoint.",
		TenantConfigGroupName: "Tenant Configuration",
		ObjectConfigGroupName: "Embed Configuration",
		tenantFieldLabel: "Tenant host (example: tenantName.eu.qlikcloud.com)",
		clientIDFieldLabel: "Client ID",
		appIDFieldLabel: "App",
		contentTypeFieldLabel: "Embed Type",
		sheetFieldLabel: "Sheet",
		optionalSheetFieldLabel: "Sheet (Optional)",
		chartFieldLabel: "Chart",
		assistantFieldLabel: "Assistant",
		assistantLegacyFieldLabel: "Assistant Legacy Mode",
		useClassicSheetUiFieldLabel: "Use Classic Sheet UI",
		useClassicChartUiFieldLabel: "Use Classic Chart UI",
		chartSizeFieldLabel: "Embed Height",
		customChartHeightFieldLabel: "Custom Height",
		AppLocalEnvironmentSharePoint:
			"The app is running on your local environment as SharePoint web part",
		AppLocalEnvironmentTeams: "The app is running on your local environment as Microsoft Teams app",
		AppLocalEnvironmentOffice: "The app is running on your local environment in office.com",
		AppLocalEnvironmentOutlook: "The app is running on your local environment in Outlook",
		AppSharePointEnvironment: "The app is running on SharePoint page",
		AppTeamsTabEnvironment: "The app is running in Microsoft Teams",
		AppOfficeEnvironment: "The app is running in office.com",
		AppOutlookEnvironment: "The app is running in Outlook",
		UnknownEnvironment: "The app is running in an unknown environment",
	};
});
